# Generated by Django 4.1.3 on 2023-04-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_postatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='status_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='purchases.postatus'),
            preserve_default=False,
        ),
    ]
